### ISSUE TITLE
Figure out how to guard against unintentional RET press when typing fast in the symbols layer

### ISSUE THREAD

**Issue by allister-beamable** [amacleod/zmk-config#10]
Sometimes when I am typing fast, especially when I end a sentence with a question mark, I end up hitting RET instead of Space, since the same key is space in my alpha layer and return in the symbol layer.

So as I am typing, I type a bunch of alphabet letters fast, followed by the question mark in my symbols layer, then, intending to press space to start a new sentence, if my thumb is still on the momentary hold for SYM, I get return instead. In contexts like Slack or Discord, that means I unintentionally send the message earlier than I intended. Then I either have to go back and edit the message, or post the subsequent sentences in a separate message.

Could I rearrange the bindings to put return elsewhere, or maybe use some clever shenanigans to get a previous idle milliseconds requirement in there? Or maybe even a macro that types question mark and space, so I never even touch the spacebar key when quickly typing multiple sentences.

**Comment by allister-beamable** [comment]
What if question mark were a macro that typed `?` and then deactivated the symbols layer? 🤔 It might be annoying if I do legitimately want to type symbols after the question mark, but that annoyance might be worth it to avoid accidental returns. It is easy to backspace a rogue letter, but there is no taking back a rogue enter in some circumstances.

**Comment by amacleod** [comment]
I solved this by putting RET in the nav layer on the right pinky. At some point I might even make it a combo on RM3 and RM4
