### ISSUE TITLE
Consider removing Space Cadet parentheses on Lily58

### ISSUE THREAD

**Issue by allister-beamable** [amacleod/zmk-config#11]
Having a tap behavior on shift prevents using the JetBrains "find anywhere" binding of double-tapping Shift. Given that I have parentheses on the symbols layer, I probably do not need them on the dedicated shift keys also, as neat as Space Cadet parentheses are.

**Comment by amacleod** [comment]
Removed. Half the time I use the symbols layer and half the time I use Shift-9 and Shift-0 for parentheses.
