### ISSUE TITLE
Make it harder to accidentally hit Esc on Lily58

### ISSUE THREAD

**Issue by allister-beamable** [amacleod/zmk-config#13]
Too often I find myself hitting escape when I meant to type grave for `code reference stuff` in Markdown-like contexts. Sometimes that can lead to frustrating losses of work. For example, when editing a previous message in Slack, a single tap of Esc instantly discards all changes--definitely not what I want when I meant to begin a code segment in the edited message.

Come up with a way to either guard Esc from accidental presses or to definitively retrain fingers to avoid Esc in those circumstances.

**Comment by allister-beamable** [comment]
Right now I am thinking a hold-tap on the Esc key that only sends Esc after a fairly significant hold (maybe 500-600ms?), but sends backtick/grave when tapped. Some kind of tap-dance could possibly also work.

**Comment by amacleod** [comment]
What I ended up doing is putting Esc on the left encoder-capable spot, leaving the upper left corner free for grave accent and tilde. Time will tell whether that feels comfortable, but at least it solves the problem of accidental escape presses.
