### ISSUE TITLE
Lily58 Dvorak - put slash on enter key

### ISSUE THREAD

**Issue by allister-beamable** [amacleod/zmk-config#5]
Since there is an enter key on the SYM layer, losing the main layer enter key is not a hardship. My fingers expect slash and question mark to exist on the key to the right of Dvorak L (left-bracket on a QWERTY slab, just right of P)

**Comment by amacleod** [comment]
Upon reflection, I think overriding the enter key is a bad idea. I have need of Shift-Enter often enough that I am pretty sure I would end up doing the wrong thing half the time if I put slash there.
I am already used to using my symbol layer for slash on the Corne, so I can get used to that on the Lily58 as well.
